name: water_drop
description: A package for creating water drops on top of your widgets. It lets you wrap any widget with a WaterDrop and create awesome visual effect!
version: 1.0.0
homepage: https://github.com/MarcinusX/water_drop

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter